"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("wines", [
      {
        id: 21,
        wine: "Adega Cachin Peza Do Rei, Barrica, Ribeira Sacra",
        wine_slug: "adega-cachin-peza-do-rei-barrica-ribeira-sacra",
        appellation: "Ribeira Sacra",
        appellation_slug: "ribeira-sacra",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2007",
        score: 87.89,
        confidence_index: "B+",
        picture_path: "adega-cachin-peza-do-rei-barrica-ribeira-sacra",
      },
      {
        id: 22,
        wine: "Artadi, Pagos Viejos, Rioja",
        wine_slug: "artadi-pagos-viejos-rioja",
        appellation: "Rioja",
        appellation_slug: "rioja",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2010",
        score: 87.89,
        confidence_index: "B+",
        picture_path: "artadi-pagos-viejos-rioja",
      },
      {
        id: 23,
        wine: "Agricola San Felice, Vigorello, Toscana",
        wine_slug: "agricola-san-felice-vigorello-toscana",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "dry",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2013",
        score: 91.46,
        confidence_index: "A",
        picture_path: "agricola-san-felice-vigorello-toscana",
      },
      {
        id: 24,
        wine: "Altesino, Brunello Di Montalcino Riserva",
        wine_slug: "altesino-brunello-di-montalcino-riserva",
        appellation: "Brunello Di Montalcino Riserva",
        appellation_slug: "brunello-di-montalcino-riserva",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2012",
        score: 91.46,
        confidence_index: "C+",
        picture_path: "altesino-brunello-di-montalcino-riserva",
      },
      {
        id: 25,
        wine: "Biserno, Tenuta di Biserno, Lodovico, Toscana",
        wine_slug: "biserno-tenuta-di-biserno-lodovico-toscana",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2013",
        score: 95.62,
        confidence_index: "B",
        picture_path: "biserno-tenuta-di-biserno-lodovico-toscana",
      },
      {
        id: 26,
        wine: "Bodegas Aalto, Ribera Del Duero",
        wine_slug: "bodegas-aalto-ribera-del-duero",
        appellation: "Ribera Del Duero",
        appellation_slug: "ribera-del-duero",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2011",
        score: 92.01,
        confidence_index: "B",
        picture_path: "bodegas-aalto-ribera-del-duero",
      },
      {
        id: 27,
        wine: "Bodegas Roda, Cirsion, Rioja",
        wine_slug: "bodegas-roda-cirsion-rioja",
        appellation: "Rioja",
        appellation_slug: "rioja",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2001",
        score: 94.33,
        confidence_index: "C+",
        picture_path: "bodegas-roda-cirsion-rioja",
      },
      {
        id: 28,
        wine: "Bodegas Roda, 'Roda I' Reserva, Rioja",
        wine_slug: "bodegas-roda-roda-i-reserva-rioja",
        appellation: "Rioja",
        appellation_slug: "rioja",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2001",
        score: 90.47,
        confidence_index: "C+",
        picture_path: "bodegas-roda-roda-i-reserva-rioja",
      },
      {
        id: 29,
        wine: "Bodegas Valdesil, Pezas Da Portela Godello, Blanco, Valdeorras",
        wine_slug:
          "bodegas-valdesil-pezas-da-portela-godello-blanco-valdeorras",
        appellation: "Valdeorras",
        appellation_slug: "valdeorras",
        color: "White",
        wine_type: "dry",
        regions: "Spain",
        country: "Spain",
        vintage: "2004",
        score: 90.96,
        confidence_index: "A",
        picture_path:
          "bodegas-valdesil-pezas-da-portela-godello-blanco-valdeorras",
      },
      {
        id: 30,
        wine: "Casanova Di Neri, Cerretalto, Brunello Di Montalcino",
        wine_slug: "casanova-di-neri-cerretalto-brunello-di-montalcino",
        appellation: "Brunello Di Montalcino",
        appellation_slug: "brunello-di-montalcino",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2012",
        score: 96.85,
        confidence_index: "B",
        picture_path: "casanova-di-neri-cerretalto-brunello-di-montalcino",
      },
      {
        id: 31,
        wine: "Casanova Di Neri, Cerretalto, Brunello Di Montalcino",
        wine_slug: "casanova-di-neri-cerretalto-brunello-di-montalcino",
        appellation: "Brunello Di Montalcino",
        appellation_slug: "brunello-di-montalcino",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2013",
        score: 93.6,
        confidence_index: "B+",
        picture_path: "casanova-di-neri-cerretalto-brunello-di-montalcino2",
      },
      {
        id: 32,
        wine: "Castello Banfi, Poggio All'Oro, Brunello Di Montalcino Riserva",
        wine_slug:
          "castello-banfi-poggio-alloro-brunello-di-montalcino-riserva",
        appellation: "Brunello Di Montalcino Riserva",
        appellation_slug: "brunello-di-montalcino-riserva",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2012",
        score: 92.85,
        confidence_index: "B",
        picture_path:
          "castello-banfi-poggio-alloro-brunello-di-montalcino-riserva",
      },
      {
        id: 33,
        wine: "Celler Pasanau, Finca la Planeta, Priorat",
        wine_slug: "celler-pasanau-finca-la-planeta-priorat",
        appellation: "Priorat",
        appellation_slug: "priorat",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2003",
        score: 89.08,
        confidence_index: "B",
        picture_path: "celler-pasanau-finca-la-planeta-priorat",
      },
      {
        id: 34,
        wine: "Dominio De Pingus, Psi, Ribera Del Duero",
        wine_slug: "dominio-de-pingus-psi-ribera-del-duero",
        appellation: "Ribera Del Duero",
        appellation_slug: "ribera-del-duero",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2009",
        score: 90.96,
        confidence_index: "B",
        picture_path: "dominio-de-pingus-psi-ribera-del-duero",
      },
      {
        id: 35,
        wine: "Dominio De Pingus, Ribera Del Duero",
        wine_slug: "dominio-de-pingus-ribera-del-duero",
        appellation: "Ribera Del Duero",
        appellation_slug: "ribera-del-duero",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "1998",
        score: 92.25,
        confidence_index: "C+",
        picture_path: "dominio-de-pingus-ribera-del-duero-1998",
      },
      {
        id: 36,
        wine: "Fattoria Poggio Di Sotto, Brunello Di Montalcino Riserva",
        wine_slug: "fattoria-poggio-di-sotto-brunello-di-montalcino-riserva",
        appellation: "Brunello Di Montalcino Riserva",
        appellation_slug: "brunello-di-montalcino-riserva",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2012",
        score: 95.8,
        confidence_index: "B",
        picture_path: "fattoria-poggio-di-sotto-brunello-di-montalcino-riserva",
      },
      {
        id: 37,
        wine: "Finca Allende, Aurus, Rioja",
        wine_slug: "finca-allende-aurus-rioja",
        appellation: "Rioja",
        appellation_slug: "rioja",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2001",
        score: 94.64,
        confidence_index: "A",
        picture_path: "finca-allende-aurus-rioja",
      },
      {
        id: 38,
        wine: "Finca Allende, Calvario, Rioja",
        wine_slug: "finca-allende-calvario-rioja",
        appellation: "Rioja",
        appellation_slug: "rioja",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2000",
        score: 91.17,
        confidence_index: "B+",
        picture_path: "finca-allende-calvario-rioja",
      },
      {
        id: 39,
        wine: "Fuligni, Brunello Di Montalcino Riserva",
        wine_slug: "fuligni-brunello-di-montalcino-riserva",
        appellation: "Brunello Di Montalcino Riserva",
        appellation_slug: "brunello-di-montalcino-riserva",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2012",
        score: 96.9,
        confidence_index: "C+",
        picture_path: "fuligni-brunello-di-montalcino-riserva",
      },
      {
        id: 40,
        wine: "Gaja, Sperss, Langhe",
        wine_slug: "gaja-sperss-langhe",
        appellation: "Langhe",
        appellation_slug: "langhe",
        color: "Red",
        wine_type: "",
        regions: "Piedmont",
        country: "Italy",
        vintage: "1990",
        score: 95.4,
        confidence_index: "A",
        picture_path: "gaja-sperss-langhe",
      },
      {
        id: 41,
        wine: "Isole e Olena, Cepparello, Toscana",
        wine_slug: "isole-e-olena-cepparello-toscana",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2014",
        score: 93.53,
        confidence_index: "B",
        picture_path: "isole-e-olena-cepparello-toscana",
      },
      {
        id: 42,
        wine: "La Rioja Alta, Gran Reserva 904, Rioja",
        wine_slug: "la-rioja-alta-gran-reserva-904-rioja",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "1985",
        score: 88.59,
        confidence_index: "C",
        picture_path: "la-rioja-alta-gran-reserva-904-rioja",
      },
      {
        id: 43,
        wine: "Luce della Vite, Luce, Toscana",
        wine_slug: "luce-della-vite-luce-toscana",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2015",
        score: 93.13,
        confidence_index: "B",
        picture_path: "luce-della-vite-luce-toscana",
      },
      {
        id: 44,
        wine: "Marchesi Antinori, Tenuta Guado al Tasso, Il Bruciato, Bolgheri",
        wine_slug:
          "marchesi-antinori-tenuta-guado-al-tasso-il-bruciato-bolgheri",
        appellation: "Bolgheri",
        appellation_slug: "bolgheri",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2016",
        score: 90.28,
        confidence_index: "B",
        picture_path:
          "marchesi-antinori-tenuta-guado-al-tasso-il-bruciato-bolgheri",
      },
      {
        id: 45,
        wine: "Marchesi Antinori, Tenuta Guado al Tasso, Cont' Ugo, Bolgheri",
        wine_slug: "marchesi-antinori-tenuta-guado-al-tasso-cont-ugo-bolgheri",
        appellation: "Bolgheri",
        appellation_slug: "bolgheri",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2015",
        score: 91.87,
        confidence_index: "B",
        picture_path:
          "marchesi-antinori-tenuta-guado-al-tasso-cont-ugo-bolgheri",
      },
      {
        id: 46,
        wine: "Montevertine, Le Pergole Torte, Toscana",
        wine_slug: "montevertine-le-pergole-torte-toscana",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2015",
        score: 91.87,
        confidence_index: "B",
        picture_path: "montevertine-le-pergole-torte-toscana-2015",
      },
      {
        id: 47,
        wine: "Montevertine, Le Pergole Torte, Toscana",
        wine_slug: "montevertine-le-pergole-torte-toscana",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2013",
        score: 97.16,
        confidence_index: "A",
        picture_path: "montevertine-le-pergole-torte-toscana",
      },
      {
        id: 48,
        wine: "Numanthia, Termes, Toro",
        wine_slug: "numanthia-termes-toro",
        appellation: "Toro",
        appellation_slug: "toro",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2009",
        score: 91.51,
        confidence_index: "A",
        picture_path: "numanthia-termes-toro",
      },
      {
        id: 49,
        wine: "Numanthia, Toro",
        wine_slug: "numanthia-toro",
        appellation: "Toro",
        appellation_slug: "toro",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2007",
        score: 92.32,
        confidence_index: "A",
        picture_path: "numanthia-toro",
      },
      {
        id: 50,
        wine: "Tenuta Fanti, Le Macchiarelle, Brunello Di Montalcino Riserva",
        wine_slug:
          "tenuta-fanti-le-macchiarelle-brunello-di-montalcino-riserva",
        appellation: "Brunello Di Montalcino Riserva",
        appellation_slug: "brunello-di-montalcino-riserva",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2012",
        score: 92.84,
        confidence_index: "B",
        picture_path:
          "tenuta-fanti-le-macchiarelle-brunello-di-montalcino-riserva",
      },
      {
        id: 51,
        wine: "Tenuta il Poggione, Brunello Di Montalcino",
        wine_slug: "tenuta-il-poggione-brunello-di-montalcino",
        appellation: "Brunello Di Montalcino",
        appellation_slug: "brunello-di-montalcino",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2013",
        score: 94.97,
        confidence_index: "B",
        picture_path: "tenuta-il-poggione-brunello-di-montalcino",
      },
      {
        id: 52,
        wine: "Tenuta il Poggione, Vigna Paganelli, Brunello Di Montalcino Riserva",
        wine_slug:
          "tenuta-il-poggione-vigna-paganelli-brunello-di-montalcino-riserva",
        appellation: "Brunello Di Montalcino Riserva",
        appellation_slug: "brunello-di-montalcino-riserva",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2012",
        score: 95.64,
        confidence_index: "A",
        picture_path:
          "tenuta-il-poggione-vigna-paganelli-brunello-di-montalcino-riserva",
      },
      {
        id: 53,
        wine: "Tenuta San Guido, Guidalberto, Toscana",
        wine_slug: "tenuta-san-guido-guidalberto-toscana",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2016",
        score: 92.05,
        confidence_index: "B+",
        picture_path: "tenuta-san-guido-guidalberto-toscana",
      },
      {
        id: 54,
        wine: "Tenuta San Guido, Le Difese, Toscana",
        wine_slug: "tenuta-san-guido-le-difese-toscana",
        appellation: "Toscana",
        appellation_slug: "toscana",
        color: "Red",
        wine_type: "dry",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2016",
        score: 89.53,
        confidence_index: "B+",
        picture_path: "tenuta-san-guido-le-difese-toscana",
      },
      {
        id: 55,
        wine: "Torres, Grans Muralles, Conca De Barbera",
        wine_slug: "torres-grans-muralles-conca-de-barbera",
        appellation: "Conca De Barbera",
        appellation_slug: "conca-de-barbera",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2001",
        score: 92.47,
        confidence_index: "B+",
        picture_path: "torres-grans-muralles-conca-de-barbera",
      },
      {
        id: 56,
        wine: "Torres, Mas La Plana Cabernet Sauvignon, Penedes",
        wine_slug: "torres-mas-la-plana-cabernet-sauvignon-penedes",
        appellation: "Penedes",
        appellation_slug: "penedes",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2005",
        score: 90.8,
        confidence_index: "C+",
        picture_path: "torres-mas-la-plana-cabernet-sauvignon-penedes",
      },
      {
        id: 57,
        wine: "Torres, Perpetual, Priorat",
        wine_slug: "torres-perpetual-priorat",
        appellation: "Priorat",
        appellation_slug: "priorat",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2010",
        score: 90.69,
        confidence_index: "B+",
        picture_path: "torres-perpetual-priorat",
      },
      {
        id: 58,
        wine: "Torres, Reserva Real, Penedes",
        wine_slug: "torres-reserva-real-penedes",
        appellation: "Penedes",
        appellation_slug: "penedes",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2006",
        score: 93.46,
        confidence_index: "B",
        picture_path: "torres-reserva-real-penedes",
      },
      {
        id: 59,
        wine: "Torres, Salmos, Priorat",
        wine_slug: "torres-salmos-priorat",
        appellation: "Priorat",
        appellation_slug: "priorat",
        color: "Red",
        wine_type: "",
        regions: "Spain",
        country: "Spain",
        vintage: "2010",
        score: 93.46,
        confidence_index: "A",
        picture_path: "torres-salmos-priorat",
      },
      {
        id: 60,
        wine: "Fuligni, Brunello Di Montalcino Riserva",
        wine_slug: "fuligni-brunello-di-montalcino",
        appellation: "Brunello Di Montalcino",
        appellation_slug: "brunello-di-montalcino",
        color: "Red",
        wine_type: "",
        regions: "Tuscany",
        country: "Italy",
        vintage: "2013",
        score: 94.4,
        confidence_index: "C+",
        picture_path: "fuligni-brunello-di-montalcino",
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete(
      "wines",
      { [Op.or]: [{ country: "Spain" }, { country: "Italy" }] },
      {}
    );
  },
};
