"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("wines", [
      {
        id: 2,
        wine: "Chateau De Fargues, Blanc, Sauternes",
        wine_slug: "chateau-de-fargues-blanc-sauternes",
        appellation: "Sauternes",
        appellation_slug: "sauternes",
        color: "White",
        wine_type: "sweet",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 94.38,
        confidence_index: "B",
        picture_path: "chateau-de-fargues-blanc-sauternes",
      },
      {
        id: 3,
        wine: "Chateau Coutet, Blanc, Barsac",
        wine_slug: "chateau-coutet-blanc-barsac",
        appellation: "Barsac",
        appellation_slug: "barsac",
        color: "White",
        wine_type: "sweet",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 92.67,
        confidence_index: "B",
        picture_path: "chateau-coutet-blanc-barsac",
      },
      {
        id: 4,
        wine: "Chateau La Tour Blanche, Blanc, Sauternes",
        wine_slug: "chateau-la-tour-blanche-blanc-sauternes",
        appellation: "Sauternes",
        appellation_slug: "sauternes",
        color: "White",
        wine_type: "sweet",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 92.54,
        confidence_index: "A+",
        picture_path: "chateau-la-tour-blanche-blanc-sauternes",
      },
      {
        id: 5,
        wine: "Chateau Doisy Vedrines, Blanc, Sauternes",
        wine_slug: "chateau-doisy-vedrines-blanc-sauternes",
        appellation: "Sauternes",
        appellation_slug: "sauternes",
        color: "White",
        wine_type: "sweet",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 91.99,
        confidence_index: "B",
        picture_path: "chateau-doisy-vedrines-blanc-sauternes",
      },
      {
        id: 6,
        wine: "Chateau La Fleur Peyrabon, Pauillac",
        wine_slug: "chateau-la-fleur-peyrabon-pauillac",
        appellation: "Pauillac",
        appellation_slug: "pauillac",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 88.12,
        confidence_index: "C+",
        picture_path: "chateau-la-fleur-peyrabon-pauillac",
      },
      {
        id: 7,
        wine: "Chateau Canon, Saint Emilion Grand Cru",
        wine_slug: "chateau-canon-saint-emilion-grand-cru",
        appellation: "Saint Emilion Grand Cru",
        appellation_slug: "saint-emilion-grand-cru",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 98.61,
        confidence_index: "A+",
        picture_path: "chateau-canon-saint-emilion-grand-cru",
      },
      {
        id: 8,
        wine: "Chateau Trotanoy, Pomerol",
        wine_slug: "chateau-trotanoy-pomerol",
        appellation: "Pomerol",
        appellation_slug: "pomerol",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 98.28,
        confidence_index: "A",
        picture_path: "chateau-trotanoy-pomerol",
      },
      {
        id: 9,
        wine: "Chateau Haut Brion, Pessac Leognan",
        wine_slug: "chateau-haut-brion-pessac-leognan",
        appellation: "Pessac Leognan",
        appellation_slug: "pessac-leognan",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 98.25,
        confidence_index: "B+",
        picture_path: "chateau-haut-brion-pessac-leognan",
      },
      {
        id: 10,
        wine: "Chateau La Mission Haut Brion, Pessac Leognan",
        wine_slug: "chateau-la-mission-haut-brion-pessac-leognan",
        appellation: "Pessac Leognan",
        appellation_slug: "pessac-leognan",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 98.21,
        confidence_index: "A+",
        picture_path: "chateau-la-mission-haut-brion-pessac-leognan",
      },
      {
        id: 11,
        wine: "Chateau Margaux, Margaux",
        wine_slug: "chateau-margaux-margaux",
        appellation: "Margaux",
        appellation_slug: "margaux",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 98.1,
        confidence_index: "A",
        picture_path: "chateau-margaux-margaux",
      },
      {
        id: 12,
        wine: "Chateau Mouton Rothschild, Pauillac",
        wine_slug: "chateau-mouton-rothschild-pauillac",
        appellation: "Pauillac",
        appellation_slug: "pauillac",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.94,
        confidence_index: "A+",
        picture_path: "chateau-mouton-rothschild-pauillac",
      },
      {
        id: 13,
        wine: "Chateau Angelus, Saint Emilion Grand Cru",
        wine_slug: "chateau-angelus-saint-emilion-grand-cru",
        appellation: "Saint Emilion Grand Cru",
        appellation_slug: "saint-emilion-grand-cru",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.72,
        confidence_index: "A",
        picture_path: "chateau-angelus-saint-emilion-grand-cru",
      },
      {
        id: 14,
        wine: "Vieux Chateau Certan, Pomerol",
        wine_slug: "vieux-chateau-certan-pomerol",
        appellation: "Pomerol",
        appellation_slug: "Pomerol",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.51,
        confidence_index: "B+",
        picture_path: "vieux-chateau-certan-pomerol",
      },
      {
        id: 15,
        wine: "Chateau L'Eglise Clinet, Pomerol",
        wine_slug: "chateau-leglise-clinet-pomerol",
        appellation: "Pomerol",
        appellation_slug: "pomerol",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.49,
        confidence_index: "A+",
        picture_path: "chateau-leglise-clinet-pomerol",
      },
      {
        id: 16,
        wine: "Chateau Smith Haut Lafitte, Pessac Leognan",
        wine_slug: "chateau-smith-haut-lafitte-pessac-leognan",
        appellation: "Pessac Leognan",
        appellation_slug: "pessac-leognan",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.44,
        confidence_index: "A+",
        picture_path: "chateau-smith-haut-lafitte-pessac-leognan",
      },
      {
        id: 17,
        wine: "Chateau Pavie, Saint Emilion Grand Cru",
        wine_slug: "chateau-pavie-saint-emilion-grand-cru",
        appellation: "Saint Emilion Grand Cru",
        appellation_slug: "saint-emilion-grand-cru",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.43,
        confidence_index: "A+",
        picture_path: "chateau-pavie-saint-emilion-grand-cru",
      },
      {
        id: 18,
        wine: "Chateau Ducru Beaucaillou, Saint Julien",
        wine_slug: "chateau-ducru-beaucaillou-saint-julien",
        appellation: "Saint Julien",
        appellation_slug: "saint-julien",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.24,
        confidence_index: "A",
        picture_path: "chateau-ducru-beaucaillou-saint-julien",
      },
      {
        id: 19,
        wine: "Chateau Lafite Rothschild, Pauillac",
        wine_slug: "chateau-lafite-rothschild-pauillac",
        appellation: "Pauillac",
        appellation_slug: "pauillac",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.15,
        confidence_index: "A+",
        picture_path: "chateau-lafite-rothschild-pauillac",
      },
      {
        id: 20,
        wine: "Chateau Belair-Monange, Saint Emilion Grand Cru",
        wine_slug: "chateau-belair-monange-saint-emilion-grand-cru",
        appellation: "Saint Emilion Grand Cru",
        appellation_slug: "saint-emilion-grand-cru",
        color: "Red",
        wine_type: "",
        regions: "Bordeaux",
        country: "France",
        vintage: "2020",
        score: 97.12,
        confidence_index: "A",
        picture_path: "chateau-belair-monange-saint-emilion-grand-cru",
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("wines", { country: "France" }, {});
  },
};
